# Generated by Django 6.0.2 on 2026-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='Active', max_length=20),
        ),
    ]
