# Generated by Django 6.0.2 on 2026-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetotp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
